quiet: true
with-expecter: true
disable-config-search: true
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}Mock"
filename: "{{.InterfaceName | snakecase}}_mock.go"
outpkg: "mocks"
packages:
  geeksonator/internal/observer:
    interfaces:
        BotProvider:
        Cache:
  geeksonator/internal/provider/telegram:
    interfaces:
        BotAPI:
