// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
)

// BotAPIMock is an autogenerated mock type for the BotAPI type
type BotAPIMock struct {
	mock.Mock
}

type BotAPIMock_Expecter struct {
	mock *mock.Mock
}

func (_m *BotAPIMock) EXPECT() *BotAPIMock_Expecter {
	return &BotAPIMock_Expecter{mock: &_m.Mock}
}

// GetChatAdministrators provides a mock function with given fields: config
func (_m *BotAPIMock) GetChatAdministrators(config tgbotapi.ChatAdministratorsConfig) ([]tgbotapi.ChatMember, error) {
	ret := _m.Called(config)

	var r0 []tgbotapi.ChatMember
	var r1 error
	if rf, ok := ret.Get(0).(func(tgbotapi.ChatAdministratorsConfig) ([]tgbotapi.ChatMember, error)); ok {
		return rf(config)
	}
	if rf, ok := ret.Get(0).(func(tgbotapi.ChatAdministratorsConfig) []tgbotapi.ChatMember); ok {
		r0 = rf(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tgbotapi.ChatMember)
		}
	}

	if rf, ok := ret.Get(1).(func(tgbotapi.ChatAdministratorsConfig) error); ok {
		r1 = rf(config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BotAPIMock_GetChatAdministrators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatAdministrators'
type BotAPIMock_GetChatAdministrators_Call struct {
	*mock.Call
}

// GetChatAdministrators is a helper method to define mock.On call
//   - config tgbotapi.ChatAdministratorsConfig
func (_e *BotAPIMock_Expecter) GetChatAdministrators(config interface{}) *BotAPIMock_GetChatAdministrators_Call {
	return &BotAPIMock_GetChatAdministrators_Call{Call: _e.mock.On("GetChatAdministrators", config)}
}

func (_c *BotAPIMock_GetChatAdministrators_Call) Run(run func(config tgbotapi.ChatAdministratorsConfig)) *BotAPIMock_GetChatAdministrators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(tgbotapi.ChatAdministratorsConfig))
	})
	return _c
}

func (_c *BotAPIMock_GetChatAdministrators_Call) Return(_a0 []tgbotapi.ChatMember, _a1 error) *BotAPIMock_GetChatAdministrators_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BotAPIMock_GetChatAdministrators_Call) RunAndReturn(run func(tgbotapi.ChatAdministratorsConfig) ([]tgbotapi.ChatMember, error)) *BotAPIMock_GetChatAdministrators_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: c
func (_m *BotAPIMock) Send(c tgbotapi.Chattable) (tgbotapi.Message, error) {
	ret := _m.Called(c)

	var r0 tgbotapi.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(tgbotapi.Chattable) (tgbotapi.Message, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(tgbotapi.Chattable) tgbotapi.Message); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(tgbotapi.Message)
	}

	if rf, ok := ret.Get(1).(func(tgbotapi.Chattable) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BotAPIMock_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type BotAPIMock_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - c tgbotapi.Chattable
func (_e *BotAPIMock_Expecter) Send(c interface{}) *BotAPIMock_Send_Call {
	return &BotAPIMock_Send_Call{Call: _e.mock.On("Send", c)}
}

func (_c *BotAPIMock_Send_Call) Run(run func(c tgbotapi.Chattable)) *BotAPIMock_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(tgbotapi.Chattable))
	})
	return _c
}

func (_c *BotAPIMock_Send_Call) Return(_a0 tgbotapi.Message, _a1 error) *BotAPIMock_Send_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BotAPIMock_Send_Call) RunAndReturn(run func(tgbotapi.Chattable) (tgbotapi.Message, error)) *BotAPIMock_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewBotAPIMock creates a new instance of BotAPIMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBotAPIMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *BotAPIMock {
	mock := &BotAPIMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
